controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      #type: velocity_controllers/JointPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - bot_slider_l_joint
      - bot_slider_r_joint

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: cart_imu_sensor
    frame_id: imu
